### ISSUE TITLE
how do you handle multiple domains for domain classification loss? 

### ISSUE THREAD

**Issue by wise-east** [clovaai/som-dst#11]
I am wondering how you can handle multiple domains for domain classification loss. In the paper, you describe using a one-hot vector to represent the label. So if the target is multi-domain, e.g. restaurant + hotel, is the one hot vector containing multiple ones, e.g. [1, 1, 0, 0, 0] ?

**Comment by DSKSD** [comment]
Hi!
I just followed the preprocessing procedure provided by the [TRADE-dst](https://github.com/jasonwu0731/trade-dst/blob/master/create_data.py). The authors of the TRADE also recognized that there might be multiple-domains cases in a turn but ignored the cases for the simplicity. Please see https://github.com/clovaai/som-dst/blob/master/create_data.py#L344 .
